feat(webapp): add create_org_redirect
TheNileDev/examples pull request #153
Opened 2022-12-07 18:52 UTC by jrea

### Description

adds a goofy server to circumvent what our auth model does.

This assumes: 

your google SSO urls are something like: `http://local.thenile.dev/create_org_redirect?org=org_02rjtC93J3Ew0aPsr3IuRH`
You have created a workspace token and put it into `.env`. Sticking your nile developer creds in there seems bad.

Does not:
use cookie authentication to verify you're a valid nile user. the endpoint is open to the world. Maybe that's bad for a publicly hosted demo, but not spending the time now to fix something of that nature.

_What behavior does this PR change, and why?_

_Note any breaking changes_

### Checklist before merge

### Submitter Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

2022-12-07 20:55 UTC, ybyzek commented on webapp/pages/api/addSsoUser.ts
> +    console.log(response);
@jrea this is printed to the console...do we want to maybe comment this line out?

2022-12-07 21:00 UTC, ybyzek commented on webapp/pages/api/addSsoUser.ts
> +    }).connect(process.env.NILE_WORKSPACE_ACCESS_TOKEN);
@jrea for a negative test to see what happens with the wrong token, the webapp loops with weird errors.  Is there a better error handling path?

<img width="1702" alt="Screen Shot 2022-12-07 at 15 59 57" src="https://user-images.githubusercontent.com/12448600/206294538-acc4b548-3b16-4e05-9716-88d057449cd5.png">

2022-12-07 21:03 UTC, jrea commented on webapp/pages/api/addSsoUser.ts
> +    console.log(response);
I'm inclined to leave it. if you already add a user, the server tells you, but we still do a 200, since that's ok for our purposes.

2022-12-07 21:16 UTC, jrea commented on webapp/pages/api/addSsoUser.ts
> +    }).connect(process.env.NILE_WORKSPACE_ACCESS_TOKEN);
this should be fixed. its not actually null some times, I think.

2022-12-07 21:49 UTC, ybyzek commented on webapp/pages/create_org_redirect/index.tsx
> +      return fetch('/api/addSsoUser', {
@jrea see Slack, couldn't get this to work calling the BE

2022-12-08 04:24 UTC, ybyzek requested changes
Do not merge until https://github.com/TheNileDev/examples/pull/155 is merged in first

2022-12-08 15:30 UTC, closed without merging