feat(data-plane/pulumi): run reconciler as yarn start or Docker
TheNileDev/examples pull request #17
Opened 2022-08-29 15:58 UTC by ybyzek

Provide other ways to run the reconciler more simply: as `yarn run start` or Docker image.

The fact that this reconciler example uses `oclif` is an implementation detail, and it is a future work item to evaluate whether to replace it.

2022-08-29 17:28 UTC, ybyzek commented on data-plane/pulumi/src/reconciler.ts
> +const basePath = process.env.NILE_URL || '';
Open to feedback on how to ensure these values are defined.

Without `|| ''`, it errors out with:

```
Type 'string | undefined' is not assignable to type 'string'.
```

2022-08-29 18:02 UTC, ybyzek commented on data-plane/pulumi/yarn.lock
> +  "integrity" "sha512-qRmjj8nj9qmLTQXXmaR1cck3UXSRMPrbsLJAasZpF+t3riI71BXed5ebIOYwQntykeZuhjsdweEc9BxH5Jc26w=="
I think the ordering here is just what's different, not the values.  Any idea on how to not do this (to avoid the unnecessary massive diff)?

2022-08-31 19:15 UTC, scottydawg requested changes

2022-08-31 20:24 UTC, ybyzek reviewed
@scottydawg thanks for your feedback, addressed in latest commit.

2022-08-31 20:24 UTC, ybyzek commented on data-plane/pulumi/README.md
> +yarn run start
Agree, and fixed in latest commit.

2022-08-31 20:24 UTC, ybyzek commented on data-plane/pulumi/README.md
> +```
@scottydawg for background: the reasoning behind current implementation was to move towards running all the examples in a similar way with a common input file of `.env`.  So a user could just have a single `.env` file and then can run any example.  (In fact, as a near term next step, I'd like to convert the nodejs_quickstart from constants to this `.env` method as well.)

For the reconciler binary, I didn't want to modify the code as it was because we already have users running `reconciler` a certain way, so I didn't want to change it to use the env parameters and not pass in the input parameters.  As the PR is right now, it might be a little sub-optimal but provides backward compatibility with what users are expecting from today.

2022-08-31 20:24 UTC, ybyzek commented on data-plane/pulumi/src/reconciler.ts
> +}
@scottydawg really awesome code improvement!  Implemented in latest commit (though note tiny change with defining the list of env params).

2022-08-31 20:47 UTC, scottydawg commented on data-plane/pulumi/README.md
> +```
As a developer looking at this the first time, my question was, "Why do I need to pass these arguments if they're already environment variables?" If I go through the work of setting that thing up, I'd expect the process to be able to find them for me. It just left me scratching my head a bit. If this is a temporary thing, I get it, but I wouldn't leave it that way for long.

2022-08-31 20:48 UTC, scottydawg approved these changes

2022-08-31 21:09 UTC, ybyzek commented on data-plane/pulumi/README.md
> +```
@scottydawg I agree it's suboptimal, and it should be temporary for a short period of time till we agree we can change the user's current workflow.

2022-08-31 21:10 UTC, merged