docs(data-plane/pulumi): add description of what happens if reconcile…
TheNileDev/examples pull request #19
Opened 2022-08-31 17:58 UTC by ybyzek

…r stops and restarts

Added explanation to README.md

2022-08-31 19:29 UTC, scottydawg commented on data-plane/pulumi/README.md
> +- _Existing_ entity instances that were updated will not be reconciled in the data plane. It is left to the developer to apply their own logic to detect a significant change (e.g. use `instanceEvents
The really confusing scenario I discovered recently is after you delete everything in your control plane while the agent is not running. When you start back up that point, `loadNileEntities()` is empty—which makes sense, but that means we don't have a way to know what the last instance `seqNum` is. So we start listening for events from sequence #0, which will give us the entire instance history—every create and destroy.

@norwood and I have talked about some sort of envelope for the `listInstances()` API. Right now it just returns a list of instances, but we need something like:
```json
{
  "instances": [ // the list from the current response ],
  "lastSeq": 42
}
```

That's something we'll need to figure out on the API side, and doesn't need to block this PR. I don't know if you want to try to explain that to customers here, and this README addition is a definite improvement, so this isn't a blocker. Just something to be aware of.

2022-08-31 19:29 UTC, scottydawg approved these changes

2022-08-31 19:47 UTC, gwenshap requested changes
I like the structure and the way you message it. 

I'd like to be sure that:
1. That the example handles deletes correctly in the scenario that you described. 
2. I'm concerned with the suggestion you gave on how to detect updates since it is so different from the rest of the example and we don't have an example on how to do what you suggested.

2022-08-31 19:47 UTC, gwenshap commented on data-plane/pulumi/README.md
> +- _Old_ entity instances that were deleted will be reconciled in the data plane
@ybyzek did you validate that this is true?

2022-08-31 19:47 UTC, gwenshap commented on data-plane/pulumi/README.md
> +- _Existing_ entity instances that were updated will not be reconciled in the data plane. It is left to the developer to apply their own logic to detect a significant change (e.g. use `instanceEvents
We have an initialization phase in the example that runs only once when the agent states: https://github.com/TheNileDev/examples/blob/main/data-plane/pulumi/src/commands/reconcile/index.ts#L38-L65

From what I see, this section doesn't use events at all (they are only used in `listenForNileEvents`. 

So I think pointing developers to `instanceEvents()` is inconsistent with existing patterns and may cause more confusion? 

If I am to try to fit "instance was updated" into the existing initialization, I'll use the existing pattern of comparing list of instances in CP to stacks in DP. So comparing one state to another. 

In this scenario, it isn't `before` and `after` but rather "CP state" to "DP state" or "required state" to "actual state" (the last one  is Goldsky terminilogy)

My solution in detail:
- ReconcilePlan.ts already populates `toDelete` and `toCreate` by loading instances (not events) from Nile, getting Stacks from Pulumi, and comparing them. 
- I'd add another list `toUpdate` that compares meaningful fields (size? are there other fields?) and not just the name. 
- add code to `synchronizeDataPlane` that calls my update logic (just like we call `this.deployment.destroyStack(id);`

I don't know how many of these pointers you want to share... but I wanted you to have more detailed view. 
Let me know if this isn't helpful in a review.

2022-08-31 22:05 UTC, ybyzek commented on data-plane/pulumi/README.md
> +- _Old_ entity instances that were deleted will be reconciled in the data plane
@gwenshap Yes, this worked in my environment.  When reconciler was not running, I deleted an entity instance and then rereran the reconciler: it destroyed the corresponding stack in Pulumi.  Is there a reason to think this might not have worked?

2022-09-01 00:24 UTC, ybyzek commented
@scottydawg @gwenshap latest commit updates the README to be less prescriptive on a solution, but I also captured each of your points internally in Notion so that we can iterate and figure out the best way to address them.

2022-09-01 14:28 UTC, scottydawg commented on data-plane/pulumi/README.md
> +- _Old_ entity instances that were deleted will be reconciled in the data plane
@ybyzek I observed the same.

2022-09-01 14:28 UTC, scottydawg approved these changes

2022-09-01 17:02 UTC, merged