feat(webapp): add styles
TheNileDev/examples pull request #71
Opened 2022-10-05 14:56 UTC by jrea

### Description 
yeet.
_What behavior does this PR change, and why?_

_Note any breaking changes_

### Checklist before merge

### Submitter Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

2022-10-05 15:09 UTC, ybyzek requested changes
@jrea super 🔥 snazzy!

Some comments:

1. The metrics page doesn't all fit on my laptop screen which makes it hard to grok and hard to screenshot.  Can they be resized smaller or return to side by side?
2. The boxes/tiles under the different environments are different sizes.  Is it possible to make them all consistent in size?
3. The "upgrade now" box: can it be made it smaller?  It's distracting from the rest of the page which is more important
4. The "upgrade now" box: can it be shown just on the homepage, not other pages?
5. The signup page is so cool (all those descriptions) but also runs off the page.  Maybe let's nuke one (or two if needed) of the value prop listings so it all fits.
6. I tried to signup a new user but that new user can't log in.  No errors in developer tools

2022-10-05 15:13 UTC, ybyzek commented on webapp/pages/_app.tsx
> +            <title>SaaSDB (built on Nile)</title>
```suggestion
            <title>My SaaS (built on Nile)</title>
```

2022-10-05 15:13 UTC, ybyzek commented on webapp/components/NavBar/RightSidebar/QuotaArc.tsx
> +/** make based on the sizes of the SaasDBs, to a quota */
```suggestion
/** make based on the sizes of the entity, to a quota */
```

2022-10-05 15:13 UTC, ybyzek commented on webapp/components/EntityGridView/index.tsx
> +type Properties = {
As we discussed yesterday, this will vary by entity.  Right now the webapp can be used by all entities, but this limits it to just the new `DB` one.  We have to reconcile this I think in this PR.

2022-10-05 15:13 UTC, ybyzek commented on webapp/components/EntityGridView/index.tsx
> +                <DbCard
Maybe `DbCard` should be generically `EntityInstanceCard`?

2022-10-05 15:13 UTC, ybyzek commented on webapp/components/InstanceMetrics/InstanceMetrics.tsx
> +          <Typography level="h2">{properties?.dbName}</Typography>
What's wrong with `[instanceName]`?

2022-10-05 15:13 UTC, ybyzek commented on webapp/components/NavBar/RightSidebar/ProviderUsage.tsx
> +  const { isLoading, data: dbs } = useQuery(
Here too, `abs` can be generically renamed to `entityInstances`.  Goal is to, as far as we can, decouple code from entity type, to make it reusable

2022-10-05 15:13 UTC, ybyzek commented on webapp/components/NavBar/RightSidebar/QuotaArc.tsx
> +  const { isLoading, data: dbs } = useQuery(
Same here, rename `dbs` to generic `entityInstances` or such

2022-10-05 15:14 UTC, ybyzek commented on webapp/components/EntityGridView/index.tsx
> +  cloud: 'aws' | 'gcp' | 'azure';
If you can derive `Properties` from the `FormFields.ts` (or vice versa), then it'll be truly useable by multiple entity types.

2022-10-05 20:33 UTC, jrea commented
> The metrics page doesn't all fit on my laptop screen which makes it hard to grok and hard to screenshot. Can they be resized smaller or return to side by side?

the breakpoint for the "side by side" is will be 1388px. makes a bunch of space in the middle, but accounts for like ~98% of all desktop screens.

> The boxes/tiles under the different environments are different sizes. Is it possible to make them all consistent in size?

This is intended. `prod` is larger, since it is more important than `test`

> The "upgrade now" box: can it be made it smaller? It's distracting from the rest of the page which is more important
> The "upgrade now" box: can it be shown just on the homepage, not other pages?

I recommend closing the sidebar. Upgrade CTAs are the best.

> The signup page is so cool (all those descriptions) but also runs off the page. Maybe let's nuke one (or two if needed) of the value prop listings so it all fits.

redesigned this, hopefully it's better. Also could not repro.

> I tried to signup a new user but that new user can't log in. No errors in developer tools

are you pointed at production? unable to repro this.

2022-10-07 22:20 UTC, gwenshap approved these changes
Approved from my side. 

- Pulled branch
- yarn install && yarn dev
- Ran my demo scenario (uses "DB")
- Everything worked as expected and looked 100x better.  I didn't run into the issues that Yeva mentioned on my screen. 
- I especially love how clicking on an instance shows both the instance data and metrics. Exactly how I'd want it for my own SaaS app (For future iterations, consider introducing events too? as "recent changes" stream or something like that). 
- The right side pane is funny and a cute touch. But I need to find another fake user name - with nora@demo.io, the little circle says "no", which is a bit harsh for a demo.

2022-10-10 15:45 UTC, ybyzek approved these changes
@jrea we should merge this to be able to start using it in other assets.  Of the issues we Slacked about, none of them are blockers but good to resolve if they are quick fixes.

2022-10-10 18:11 UTC, merged