Port the data-plane k8s example to use the Python SDK.
TheNileDev/examples pull request #91
Opened 2022-10-19 15:44 UTC by Julian

### Description 

_What behavior does this PR change, and why?_

A fairly 1-1 port of the data plane example (the k8s subfolder only) to exercise the events API in the SDK.

_Note any breaking changes_

In the interest of time, this doesn't follow the original example's generation of a `FlinkDeployment` from the OpenAPI spec, it just leaves things as dictionaries. That of course could be changed.

### Checklist before merge

### Submitter Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

This is a bit more fragile than the other example -- I've seen it work here locally, but curious to hear if it works for you as well, as I hope I've understood what the example is meant to do, and I'm still seeing K8s be quite flaky (in a way which I think isn't related to the example itself). It works fine here certainly when run on the host machine.

I also didn't really do any deduplication (between the README, or spec files). There are a few ways that might make sense there obviously.

Comments of course are very welcome.

2022-10-19 20:13 UTC, ybyzek requested changes
@Julian some feedback, and hit some issues with initializing Nile that I was unable to proceed on.

2022-10-19 20:13 UTC, ybyzek commented on data-plane-python/k8s/.gitignore
> +setup_cluster.sh
What is `setup_cluster.sh` and why is it included?

2022-10-19 20:13 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +# Deploy Apache Flink to K8s with Nile Example #
Also requires addition to top-level `README.md`

2022-10-19 20:13 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +venv/bin/python -m pip install -r requirements.txt
For consistency with https://github.com/TheNileDev/examples/tree/main/authz-python, should this be on one line

```
python3 -m venv venv && venv/bin/python3 -m pip install -r requirements.txt
```

2022-10-19 20:13 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +For that purpose, at the top-level of the examples, copy the `.env.defaults` file to `.env`:
This PR is missing a symlink `.env` file like in `data-plane/k8s`

2022-10-19 20:13 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +venv/bin/python setup_nile.py
Running this results in:

```
[16:10:22] ~/git/examples/data-plane-python/k8s(PR-91) ✗: venv/bin/python setup_nile.py

Logging into Nile at http://localhost:8080, workspace demo_yeva_10, as developer ybyzek+dev10@demo.io
Traceback (most recent call last):
  File "setup_nile.py", line 198, in <module>
    asyncio.run(run())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "setup_nile.py", line 70, in run
    client = AuthenticatedClient(base_url=params["NILE_URL"], token=token.token)
AttributeError: 'Error' object has no attribute 'token'
```

2022-10-19 20:14 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +venv/bin/python setup_nile.py
Update: I did some other things and reran, and now it works.  Unfortunately I haven't been able to determine "what changed" to make this work.

2022-10-19 20:19 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +venv/bin/python setup_nile.py
Is the python equivalent of this missing from the `setup_nile.py` script?

```
  await nile.developers.createDeveloper(...)
```

2022-10-19 20:30 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +CHECK_STATUS=1 venv/bin/python reconciler.py
In my env, this errors out:

```
[16:29:30] ~/git/examples/data-plane-python/k8s(PR-91) ✗: CHECK_STATUS=1 venv/bin/python reconciler.py

✅ Logged into Nile as developer ybyzek+dev7@demo.io
Loaded instances [Instance(id='inst_02rI3oHFAQuBcUD7aPXJe5', type='FlinkDeployment', properties=JsonSchemaInstance(additional_properties={'spec': {'job': {'jarURI': 'local:///opt/flink/examples/streaming/StateMachineExample.jar', 'parallelism': 2, 'upgradeMode': 'STATELESS'}, 'jobManager': {'replicas': 2, 'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'flinkConfiguration': {'taskmanager.numberOfTaskSlots': 2}}, 'metadata': {'name': 'basic-example'}}), created=datetime.datetime(2022, 10, 19, 20, 17, 30, 213302), updated=datetime.datetime(2022, 10, 19, 20, 17, 30, 213302), seq=13005, deleted=<nile_api.types.Unset object at 0x104904790>, additional_properties={})]
✅ Got Flink deployments from Nile: [JsonSchemaInstance(additional_properties={'spec': {'job': {'jarURI': 'local:///opt/flink/examples/streaming/StateMachineExample.jar', 'parallelism': 2, 'upgradeMode': 'STATELESS'}, 'jobManager': {'replicas': 2, 'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'flinkConfiguration': {'taskmanager.numberOfTaskSlots': 2}}, 'metadata': {'name': 'basic-example'}})]
Traceback (most recent call last):
  File "reconciler.py", line 314, in <module>
    asyncio.run(run())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "reconciler.py", line 83, in run
    actual_deployments = await deployment_service.get_all()
  File "reconciler.py", line 184, in get_all
    return [_to_api_flink_deployment(each) for each in response["items"]]
  File "reconciler.py", line 184, in <listcomp>
    return [_to_api_flink_deployment(each) for each in response["items"]]
  File "reconciler.py", line 273, in _to_api_flink_deployment
    "state": k8s_deployment["status"]["jobStatus"]["state"],
KeyError: 'status'
```

2022-10-19 20:32 UTC, ybyzek commented
> I also didn't really do any deduplication (between the README, or spec files). There are a few ways that might make sense there obviously.

Good point.  I can dedupe later.

2022-10-20 12:55 UTC, Julian commented on data-plane-python/k8s/README.md
> +venv/bin/python -m pip install -r requirements.txt
Done.

2022-10-20 12:55 UTC, Julian commented on data-plane-python/k8s/README.md
> +# Deploy Apache Flink to K8s with Nile Example #
Done.

2022-10-20 12:56 UTC, Julian commented on data-plane-python/k8s/README.md
> +For that purpose, at the top-level of the examples, copy the `.env.defaults` file to `.env`:
Fixed, thanks!

2022-10-20 13:11 UTC, Julian commented on data-plane-python/k8s/README.md
> +venv/bin/python setup_nile.py
> Is the python equivalent of this missing from the setup_nile.py script?

Fixed!

> Update: I did some other things and reran, and now it works. Unfortunately I haven't been able to determine "what changed" to make this work.

That sounds like authentication failed. There's some better error handling that could be added to the script here (though some of it is blocked on https://github.com/openapi-generators/openapi-python-client/pull/593 which seems important to get merged upstream).

2022-10-20 13:12 UTC, Julian commented on data-plane-python/k8s/README.md
> +CHECK_STATUS=1 venv/bin/python reconciler.py
I tweaked this, though I've still been a bit sloppy about verifying which properties aren't required in the kubernetes JSON object. Let me know if it still raises for you, I'll have a look and see.

2022-10-21 18:34 UTC, ybyzek commented on data-plane-python/k8s/setup_nile.py
> +        client=unauthenticated,
@Julian for my education, what does this `client=unauthenticated` mean?

2022-10-21 18:36 UTC, Julian commented on data-plane-python/k8s/setup_nile.py
> +        client=unauthenticated,
There's two instances of `Client`s here -- the first one (which doesn't have a token associated with it) and the second one is an instance of `AuthenticatedClient`, so I just named the first one (that's only used for the `create_developer` and `login_developer` requests) `unauthenticated`. Does that help?

2022-10-21 18:44 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +venv/bin/python setup_nile.py
@Julian I think there might need to be some logic to handle creation of a new developer which returns a 201 code (see documentation https://www.thenile.dev/rest-api#tag/developers/operation/createDeveloper)

```
...
Message: Response(status_code=201,
...
```

Otherwise it returns an error:

```
Traceback (most recent call last):
  File "setup_nile.py", line 216, in <module>
    asyncio.run(run())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "setup_nile.py", line 73, in run
    message = json.loads(response.content)["message"]
KeyError: 'message'
```

2022-10-21 18:55 UTC, ybyzek commented on data-plane-python/k8s/setup_nile.py
> +        client=unauthenticated,
👍 makes sense.  Thanks for the explanation.

2022-10-21 18:57 UTC, Julian commented on data-plane-python/k8s/README.md
> +venv/bin/python setup_nile.py
Yes! You're correct of course, fixed now I think, I should have been checking for `400`s instead.

2022-10-21 19:00 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +CHECK_STATUS=1 venv/bin/python reconciler.py
It works now, thanks.

2022-10-21 19:06 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +venv/bin/python reconciler.py
Success!

```
[15:04:06] ~/git/examples/data-plane-python/k8s(PR-91) ✗: venv/bin/python reconciler.py 

✅ Logged into Nile as developer ybyzek+dev7@demo.io
Loaded instances [Instance(id='inst_02rJAVrplO5MZEVf0Hu4n4', type='FlinkDeployment', properties=JsonSchemaInstance(additional_properties={'spec': {'job': {'jarURI': 'local:///opt/flink/examples/streaming/StateMachineExample.jar', 'parallelism': 2, 'upgradeMode': 'STATELESS'}, 'jobManager': {'replicas': 2, 'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'flinkConfiguration': {'taskmanager.numberOfTaskSlots': 2}}, 'metadata': {'name': 'basic-example'}}), created=datetime.datetime(2022, 10, 21, 18, 57, 1, 595265), updated=datetime.datetime(2022, 10, 21, 18, 57, 1, 595265), seq=11, deleted=<nile_api.types.Unset object at 0x105884610>, additional_properties={})]
✅ Got Flink deployments from Nile: [JsonSchemaInstance(additional_properties={'spec': {'job': {'jarURI': 'local:///opt/flink/examples/streaming/StateMachineExample.jar', 'parallelism': 2, 'upgradeMode': 'STATELESS'}, 'jobManager': {'replicas': 2, 'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'flinkConfiguration': {'taskmanager.numberOfTaskSlots': 2}}, 'metadata': {'name': 'basic-example'}})]
✅ Got Flink deployments from K8s: [{'metadata': {'name': 'basic-example'}, 'spec': {'flinkConfiguration': {'taskmanager.numberOfTaskSlots': '2'}, 'job': {'state': None, 'dockerImage': None, 'environment': 'local', 'parallelism': 1, 'upgradeMode': None}, 'jobManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}, 'replicas': None}}, 'status': {'jobStatus': {'jobID': '653400d8-91c2-4a26-91c7-41021c5da225', 'state': None}}}]
{'basic-example': JsonSchemaInstance(additional_properties={'spec': {'job': {'jarURI': 'local:///opt/flink/examples/streaming/StateMachineExample.jar', 'parallelism': 2, 'upgradeMode': 'STATELESS'}, 'jobManager': {'replicas': 2, 'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'flinkConfiguration': {'taskmanager.numberOfTaskSlots': 2}}, 'metadata': {'name': 'basic-example'}})} {'basic-example': {'metadata': {'name': 'basic-example'}, 'spec': {'flinkConfiguration': {'taskmanager.numberOfTaskSlots': '2'}, 'job': {'state': None, 'dockerImage': None, 'environment': 'local', 'parallelism': 1, 'upgradeMode': None}, 'jobManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}, 'replicas': None}}, 'status': {'jobStatus': {'jobID': '653400d8-91c2-4a26-91c7-41021c5da225', 'state': None}}}}
👍 Performing initial synchronization of control plane and data plane
_ReconciliationPlan(to_create=[], to_delete=[])
👂 Listening for events for FlinkDeployment entities from sequence #11




event: InstanceEvent(timestamp=datetime.datetime(2022, 10, 21, 19, 5, 16, 479000), id=13, event_type=<InstanceEventEventType.CREATE: 'CREATE'>, before=<nile_api.types.Unset object at 0x105884610>, after=Instance(id='inst_02rJAiPuojPuTiOXh7j5ZW', type='FlinkDeployment', properties=JsonSchemaInstance(additional_properties={'spec': {'job': {'jarURI': 'local:///opt/flink/examples/streaming/StateMachineExample.jar', 'parallelism': 2, 'upgradeMode': 'STATELESS'}, 'jobManager': {'replicas': 2, 'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'flinkConfiguration': {'taskmanager.numberOfTaskSlots': 2}}, 'metadata': {'name': 'basic-example2'}}), created=datetime.datetime(2022, 10, 21, 19, 5, 16, 479000), updated=datetime.datetime(2022, 10, 21, 19, 5, 16, 479000), seq=15, deleted=<nile_api.types.Unset object at 0x105884610>, additional_properties={}), additional_properties={})
🆕 Creating FlinkDeployment
Instance(id='inst_02rJAiPuojPuTiOXh7j5ZW', type='FlinkDeployment', properties=JsonSchemaInstance(additional_properties={'spec': {'job': {'jarURI': 'local:///opt/flink/examples/streaming/StateMachineExample.jar', 'parallelism': 2, 'upgradeMode': 'STATELESS'}, 'jobManager': {'replicas': 2, 'resource': {'cpu': 1, 'memory': '2048m'}}, 'taskManager': {'resource': {'cpu': 1, 'memory': '2048m'}}, 'flinkConfiguration': {'taskmanager.numberOfTaskSlots': 2}}, 'metadata': {'name': 'basic-example2'}}), created=datetime.datetime(2022, 10, 21, 19, 5, 16, 479000), updated=datetime.datetime(2022, 10, 21, 19, 5, 16, 479000), seq=15, deleted=<nile_api.types.Unset object at 0x105884610>, additional_properties={})
```

2022-10-21 19:12 UTC, ybyzek commented on data-plane-python/k8s/README.md
> +venv/bin/python setup_nile.py
@Julian fix verified, thanks.

2022-10-21 19:13 UTC, ybyzek approved these changes
@Julian thanks for addressing all the open issues, LGTM.  You ok if I merge in?

2022-10-21 19:15 UTC, Julian commented
Awesome! Yes! Thanks for the review.

2022-10-21 19:17 UTC, merged