Port the quickstart example to use the Python SDK.
TheNileDev/examples pull request #93
Opened 2022-10-22 14:33 UTC by Julian

### Description 

_What behavior does this PR change, and why?_

This ports the `quickstart` example to use the Python SDK.

_Note any breaking changes_

Nothing is particularly new here implementation-wise, as everything but `create_user` was essentially already used in the other Python examples.

### Checklist before merge

### Submitter Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

I've run all these and seen them run successfully, though there was a spot or two in the typescript code where there's some error handling that I couldn't exercise (i.e. couldn't get the API to fail in a way to require it). In particular it was where the org file handles an org that does not come back in `listOrganizations` but for some reason only errors when being created.

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

2022-10-24 11:56 UTC, ybyzek requested changes
@Julian thanks for the PR!  Functionally all looks good.  I left minor comments, if you could kindly resolve.

2022-10-24 11:56 UTC, ybyzek commented on quickstart-python/README.md
> +For that purpose, at the top-level of the examples, copy the `.env.defaults` file to `.env`:
Can you please add a `.env` symlink  (similar to https://github.com/TheNileDev/examples/blob/main/authz-python/.env)?  (And actually I see this same thing is missing from the data-plane-python/k8s example too)

2022-10-24 11:56 UTC, ybyzek commented on quickstart-python/README.md
> +venv/bin/python src/all.py
Is it possible to also please add in the equivalent to: https://github.com/TheNileDev/examples/blob/main/quickstart/src/dev.ts ?

It is not mentioned in the README, but it is part of the consolidated script https://github.com/TheNileDev/examples/blob/main/quickstart/package.json#L23

2022-10-24 11:56 UTC, ybyzek commented on quickstart-python/src/entity_instance.py
> +        print(f"{GOOD} Created entity instance {instance!r}")
Minor: is there an easy way to "pretty print" this json output?

Current output:

```
✅ Created entity instance Instance(id='inst_02rKi94V4C660OXrqGR2m5', type='DB', properties=JsonSchemaInstance(additional_properties={'dbName': 'myDB-products', 'cloud': 'gcp', 'environment': 'prod', 'size': 100, 'connection': 'server-myDB-products:3306', 'status': 'Up'}), created=datetime.datetime(2022, 10, 24, 11, 53, 51, 978760), updated=datetime.datetime(2022, 10, 24, 11, 53, 51, 978760), seq=12, deleted=<nile_api.types.Unset object at 0x1021bc730>, additional_properties={})
```

JS output:

```
Created entity instance: {
  "id": "inst_02rKi9gMCMWda6eYz7s29L",
  "created": "2022-10-24T15:54:16.063Z",
  "updated": "2022-10-24T15:54:16.063Z",
  "seq": 20,
  "type": "DB",
  "properties": {
    "dbName": "myDB-products",
    "cloud": "gcp",
    "environment": "prod",
    "size": 100,
    "connection": "server-myDB-products:3306",
    "status": "Up"
  }
}
```

2022-10-24 12:04 UTC, ybyzek commented on quickstart-python/src/ws.py
> +def run():
If the developer hasn't been created yet, this script errors out as follows:

```
venv/bin/python src/ws.py
Traceback (most recent call last):
  File "src/ws.py", line 73, in <module>
    run()
  File "src/ws.py", line 48, in run
    client = AuthenticatedClient(base_url=params["NILE_URL"], token=token.token)
AttributeError: 'Error' object has no attribute 'token'
```

Is it possible to error out more cleanly?

This is how the JS quickstart errors out:

```
❌ Error: Failed to login to Nile as developer ybyzek+dev14@demo.io: Unauthorized
```

2022-10-24 15:54 UTC, Julian commented on quickstart-python/README.md
> +For that purpose, at the top-level of the examples, copy the `.env.defaults` file to `.env`:
Sorry, I thought I indeed added them, but it seems I missed that they're actually ignored (by a global `.gitignore` in the root of the repository here).
Should I remove that from the `.gitignore`? Or leave it and force add the files? Or other? I assume probably any `.env` files that are already here were maybe either added before https://github.com/TheNileDev/examples/blob/main/.gitignore#L105 was present, or were force added?

2022-10-24 15:54 UTC, Julian commented on quickstart-python/README.md
> +venv/bin/python src/all.py
Will have a look!

2022-10-24 16:15 UTC, Julian commented on quickstart-python/src/ws.py
> +def run():
Fixed as well, thanks -- some of this is more annoying than it should be due to the issue I linked on the last PR which improves the generator's error handling (https://github.com/openapi-generators/openapi-python-client/pull/593) Right now it does something that doesn't make a ton of sense to me by not raising an exception by default, but that's what it does today unfortunately.

I've tweaked this so it matches the JS behavior, but yeah it's not as pretty as it should be to do that (which obviously is good to have in the example since that's really the current way...).

2022-10-24 16:15 UTC, Julian commented on quickstart-python/src/entity_instance.py
> +        print(f"{GOOD} Created entity instance {instance!r}")
Fixed!

2022-10-24 16:28 UTC, Julian commented on quickstart-python/README.md
> +venv/bin/python src/all.py
OK, added this I believe.

2022-10-26 16:58 UTC, ybyzek commented on quickstart-python/README.md
> +For that purpose, at the top-level of the examples, copy the `.env.defaults` file to `.env`:
Yes, I usually force add, looks like you did that here, thanks!

2022-10-26 16:59 UTC, ybyzek commented on quickstart-python/README.md
> +venv/bin/python src/all.py
Thanks!

2022-10-26 17:00 UTC, ybyzek commented on quickstart-python/src/entity_instance.py
> +        print(f"{GOOD} Created entity instance {instance!r}")
Fantastic, thanks

2022-10-26 17:02 UTC, ybyzek approved these changes
LGTM thanks @Julian

2022-10-26 17:02 UTC, merged